@extends('layouts.master')
@section('breadcrumb','Clans')
@section('content')
<div class="table-responsive">
@foreach ($clans as $c)<div class="col-md-3"><div class="ibox"><div class="ibox-content product-box" style="margin-left:4px; background-color:#2121218f;"><div class="product-imitation" style="padding:0; background-color:#0000000d;"><img src="{{ $c->Cimg }}" class="img-circle" width="200" height="170"/></div><div class="product-desc">@if($c->user)<center><img src="{{ URL::to('/') }}/assets/a/{{ $c->user->Skin }}.png" class="img-circle mt" data-toggle="tooltip" data-placement="top" data-html="true" title="<img src='{{ URL::to('/') }}/assets/s/Skin_{{ $c->user->Skin }}.png' style='height:84px;vertical-align:middle;' /><div style='bottom:33px;float:right;'>Name: {{ $c->user->user }}</br>Level: {{ $c->user->Score }}</br>RP: {{ $c->user->RPoints }}/{{ $c->user->Score*3 }}</br>Hours Played: {{ number_format($c->user->HoursPlayed/3600) }}</br>Job: {{ General::job($c->user->Job) }}</div>" style="height:33px;"> {!! ($c->user ? $c->user->url : $c->Owner) !!} <i class="fa fa-certificate" style="color:{{ ($c->user->Status == 1 ? 'green' : 'red') }};"></i><hr>@endif
	Clan ID: <b>{{ $c->ID }}</b>
	</br>Name: <b><span style="color:#{{ $c->Color }};">{{ $c->Name }}</span></b>
	</br>Tag: <b>[{{ $c->Tag }}]</b>
	</br>HQ: <b>{{ ($c->HQ > 1 ? 'Yes' : 'No') }}</b>
	</br>Alliance: <b>@if($c->AlID == -1) No @else <span style="color:#{{ $c->AlColor }};">{{ $c->AlName }}</span> @endif</b>
	</br>Vehicles: <b>{{ $c->TotalV }}/{{ $c->SlotV }}</b>
	</br></br><small>Members: <b>{{ \App\User::where('Clan',$c->ID-1)->count() }}/{{ $c->MaxMembers }}</b></small><div class="progress" style="background-color: #21212196; border: 1px solid #54545470;"><div class="progress-bar progress-bar-striped" role="progressbar" style="width:{{ (\App\User::where('Clan',$c->ID-1)->count())*100/($c->MaxMembers) }}%; color: #cacaca; font-size: 9px;">{{ \App\User::where('Clan',$c->ID-1)->count() }}/{{ $c->MaxMembers }}</div></div>
	<small>Level: <b>{{ $c->Level }} ({{ $c->XP }}/{{ $c->Level*100 }} XP)</small></b></br><div class="progress" style="background-color: #0000001f;border: 1px solid #54545445;"><div class="progress-bar progress-bar-striped" role="progressbar" style="width:{{ ($c->XP)*100/($c->Level*100) }}%; color: #212121;"></div></div>
	<?php $s = \App\Option::where('option_name','clanAppStatus' . $c->ID)->first(); $d = (!$s || $s->option_value ? 'open' : 'close'); $s = (!$s || $s->option_value ? '<i class="fa fa-unlock" style="color:#00FA00"></i>' : '<i class="fa fa-lock" style="color:#FF1C1C"></i>'); ?>
	</br><a class="btn btn-xs btn-outline btn-primary" href="{{ route('clanListApp', ['clan' => $c->ID, 'type' => 'applications']) }}">{!! $s !!} applications</a>@if(Auth::check() && Auth::user()->Clan == $c->ID) <a class="btn btn-xs btn-outline btn-primary" href="{{ route('clanListApp', ['clan' => $c->ID, 'type' => 'resignations']) }}">resignations</a> @endif<a class="btn btn-xs btn-outline btn-primary _members" type="c" id="{{ $c->ID }}">members</a> <a @if($c->HQ == 0) disabled="disabled" class="btn btn-xs btn-outline btn-primary" @else class="btn btn-xs btn-outline btn-primary _locate clan" type="c" id="{{ $c->ID }}" @endif> @if($c->Lk == 0) <i class="fa fa-unlock" style="color:#00FA00"></i> @else <i class="fa fa-lock" style="color:#FF1C1C"></i> @endif hq location</a>
	</br><a @if($c->HQ == 0) disabled="disabled" class="btn btn-xs btn-outline btn-primary" @else class="btn btn-xs btn-outline btn-primary" href="http://rpg.linkmania.ro/assets/i/{{$c->IntX}}.png" target="_blank" @endif><i class="fa fa-image"></i> interior</a> <a class="btn btn-xs btn-outline btn-primary _lg" nms="{{ $c->Name }}" type="c" id="{{ $c->ID }}">ranks</a>
	</br><a class="btn btn-xs btn-outline btn-primary _cl" nms="{{ $c->Name }}" type="c" id="{{ $c->ID }}">logs</a></center></div></div></div></div>
@endforeach</div></br><center><div class="row"><a class="btn btn-success" href="https://www.linkmania.ro/forum/1766-clanuri/" target="_blank"><i class="fa fa-external-link"></i> clans forum link</a></div></center></br>@section('js')<script>$(function () {$('.mt').tooltip({template: '<div class="tooltip md-tooltip-main"><div class="tooltip-arrow md-arrow"></div><div class="tooltip-inner md-inner-main"></div></div>'});})</script><script src="{{ asset('assets/bootbox.min.js') }}"></script><script src="{{ asset('assets/fc.min.js') }}"></script>@endsection @endsection