@extends('layouts.master')
@section('breadcrumb','Complaints')
@section('content')
	@if($user)<h3>Complaints created by you</h3><div class="row m-t-sm"><div class="table-responsive"><table class="table"><thead><tr><th>#</th><th>Username</th><th>Impotriva</th><th>Type</th><th>Date <i class="fa fa-clock-o"></i></th><th>Status</th><th>Views</th><th>Actions</th></tr></thead><tbody>@foreach ($user as $u)<tr><td>{{ $u->id }}</td><td><img src="{{ URL::to('/') }}/assets/a/{{ $u->user->Skin }}.png" class="img-circle mt" data-toggle="tooltip" data-placement="top" title="{{ $u->user->user }} / Level: {{ $u->user->Score }}" style="height:29px;"> {!! $u->user->url !!}</td><td><img src="{{ URL::to('/') }}/assets/a/{{ $u->against->Skin }}.png" class="img-circle mt" data-toggle="tooltip" data-placement="top" title="{{ $u->against->user }} / Level: {{ $u->against->Score }}" style="height:29px;"> {!! $u->against->url !!}</td><td>{!! $u->getType !!}@if($u->complaint_type == 4) ({{ General::faction($u->complaint_faction,'name') }}) @endif / {!! $u->reason!!}</td><td>{!! $u->created_at !!}</td><td>{{ $u->View }}</td><td>{!! $u->status !!} @if($u->action) ({{ $u->action_text }}) @if($u->action_text == "Nothing")<i style="color:green" class="fa fa-smile-o"></i>@else<i style="color:red" class="fa fa-frown-o"></i>@endif  @endif</td><td><a href="{!! $u->url !!}"><i class="fa fa-external-link"></i> View</a></td></tr>@endforeach</tbody></table></div></div>@endif
	<div class="row"><a class="btn btn-success" style="float:right;" href="{{ URL::to('complaints/create') }}">Create</a></div><div class="row m-t-sm"><div class="table-responsive"><table class="table"><thead><tr><th>#</th><th>Username</th><th>Impotriva</th><th>Type</th><th>Date <i class="fa fa-clock-o"></i></th><th>Status</th><th>Views</th><th>Actions</th></tr></thead><tbody>@foreach ($complaints as $c)<tr><td>{{ $c->id }}</td><td><img src="{{ URL::to('/') }}/assets/a/{{ $c->user->Skin }}.png" class="img-circle mt" data-toggle="tooltip" data-placement="top" title="{{ $c->user->user }} / Level: {{ $c->user->Score }}" style="height:29px;"> {!! $c->user->url !!}</td><td><img src="{{ URL::to('/') }}/assets/a/{{ $c->against->Skin }}.png" class="img-circle mt" data-toggle="tooltip" data-placement="top" title="{{ $c->against->user }} / Level: {{ $c->against->Score }}" style="height:29px;"> {!! $c->against->url !!}</td><td>{!! $c->getType !!}@if($c->complaint_type == 4) ({{ General::faction($c->complaint_faction,'name') }}) @endif / {!! $c->reason!!}</td><td>{!! $c->created_at !!}</td><td>{!! $c->status !!} @if($c->action) ({{ $c->action_text }}) @if($c->action_text == "Nothing")<i style="color:green" class="fa fa-smile-o"></i>@else<i style="color:red" class="fa fa-frown-o"></i>@endif  @endif</td><td>{{ $c->View }}</td><td><a href="{!! $c->url !!}"><i class="fa fa-external-link"></i> View</a></td></tr>@endforeach</tbody></table></div></div>
	{!! $complaints->render() !!}
	
	@section('css')<link rel="stylesheet" type="text/css" href="{{ asset('assets/css/dt.min.css') }}"/>@endsection
	@section('js')<script>$(function () {$('.mt').tooltip({template: '<div class="tooltip md-tooltip-main"><div class="tooltip-arrow md-arrow"></div><div class="tooltip-inner md-inner-main"></div></div>'});})</script><script type="text/javascript" src="https://cdn.datatables.net/v/bs/dt-1.10.12/datatables.min.js"></script><script>$(document).ready(function(){$('.datatable').DataTable({iDisplayLength:5,"aLengthMenu": [[5, 10, 25, 50, 100], [5, 10, 25, 50, 100]]});});</script>@endsection
@endsection